name: rsCNN
channels:
  - defaults
  - conda-forge
dependencies:
  - absl-py=0.7.1
  - affine=2.2.2
  - astor=0.7.1
  - attrs=19.1.0
  - autopep8=1.4.4
  - blas=1.0
  - bzip2=1.0.6
  - c-ares=1.15.0
  - ca-certificates=2019.5.15
  - cairo=1.14.12
  - certifi=2019.3.9
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - curl=7.64.1
  - cycler=0.10.0
  - dbus=1.13.6
  - expat=2.2.6
  - fiona=1.8.4
  - fontconfig=2.13.0
  - freetype=2.9.1
  - freexl=1.0.5
  - gast=0.2.2
  - gdal=2.3.3
  - geos=3.7.1
  - giflib=5.1.4
  - glib=2.56.2
  - grpcio=1.16.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2019.4
  - joblib=0.13.2
  - jpeg=9b
  - json-c=0.13.1
  - kealib=1.4.7
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-base=2.2.4
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - libboost=1.67.0
  - libcurl=7.64.1
  - libdap4=3.19.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgdal=2.3.3
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=11.2
  - libprotobuf=3.8.0
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markdown=3.1.1
  - matplotlib=3.1.0
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mock=3.0.5
  - munch=2.3.2
  - ncurses=6.1
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openjpeg=2.3.0
  - openssl=1.1.1c
  - pcre=8.43
  - pip=19.1.1
  - pixman=0.38.0
  - poppler=0.65.0
  - poppler-data=0.4.9
  - proj4=5.2.0
  - protobuf=3.8.0
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyyaml=5.1
  - qt=5.9.7
  - rasterio=1.0.21
  - readline=7.0
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - setuptools=41.0.1
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.12.0
  - snuggs=1.4.6
  - sqlite=3.28.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - tk=8.6.8
  - tornado=6.0.2
  - tqdm=4.32.1
  - werkzeug=0.15.4
  - wheel=0.33.4
  - xerces-c=3.2.2
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.3.7
