name: bfgn
channels:
  - defaults
  - conda-forge
dependencies:
  - fiona>=1.8.4
  - gdal=2.3.3
  - keras=2.2.4
  - matplotlib>=3.1.0
  - numpy>=1.16.4
  - psutil>=5.4.8
  - python>=3.7.3
  - pyyaml>=5.1
  - rasterio>=1.0.21
  - scikit-learn>=0.21.2
  - scipy>=1.2.1
  - shapely>=1.6.4
  - tensorflow=1.15
  - tqdm>=4.32.1
  - albumentations>=0.5.0
  - requests
