raw_files:
  feature_files: [['scratch/dem.tif']]
  response_files: [['scratch/mound_points_utm.tif']]
  boundary_files: ['scratch/training_boundary.shp']
  feature_data_type: ['R']
  response_data_type: ['C']
  feature_nodata_value: -9999
  response_nodata_value: -9999
  boundary_bad_value: 0
  ignore_projections: false
data_build:
  dir_out: ./termite_test
  filename_prefix_out: 'munged_data'
  network_category: FCN
  random_seed: 1
  max_samples: 100
  max_memmap_size_gb: 10
  number_folds: 10
  validation_fold: 0
  test_fold: None
  window_radius: 16
  loss_window_radius: 8
  feature_mean_centering: True
  feature_nodata_maximum_fraction: 0.0
  response_min_value: 0
  response_max_value: 10000
  response_background_value: None
data_samples:
  apply_random_transformations: true
  batch_size: 100
  feature_scaler_names: ['NullScaler']
  response_scaler_names: ['NullScaler']
  feature_nodata_encoding: -10.0
model_training:
  dir_out: ./termite_test
  verbosity: 1
  assert_gpu: false
  architecture_name: unet
  loss_metric: cc
  max_epochs: 100
  optimizer: adam
  weighted: false
architecture:
  block_structure: [4, 4]
  filters: 6
  kernel_size: [3, 3]
  min_conv_width: 8
  n_classes: 1
  output_activation: linear
  padding: same
  pool_size: [2, 2]
  use_batch_norm: false
  use_growth: false
  use_initial_colorspace_transformation_layer: false
model_reporting:
  max_pages_per_figure: 1
  max_samples_per_page: 20
  max_features_per_page: 10
  max_responses_per_page: 10
  network_progression_max_pages: 1
  network_progression_max_filters: 10
  network_progression_show_full: true
  network_progression_show_compact: false
callback_general:
  checkpoint_periods: 5
  use_terminate_on_nan: true
callback_tensorboard:
  use_callback: true
  update_freq: epoch
  histogram_freq: 0
  write_graph: true
  write_grads: false
  write_images: true
callback_early_stopping:
  use_callback: true
  min_delta: 0.0001
  patience: 50
callback_reduced_learning_rate:
  use_callback: true
  factor: 0.5
  min_delta: 0.0001
  patience: 10
