data_save_name : 'examples/munged/cwc_data_ob_test'
data_build_category : 'ordered_continuous'
max_samples : 30000
window_radius : 32
internal_window_radius : 16
response_max_value : 10000
response_min_value : 0
feature_scaler_name : 'StandardScaler'
response_scaler_name : 'StandardScaler'

architecture : 'unet'
use_batch_norm : True
conv_depth : 'growth'
block_structure : [1,1]
n_layers : 10
output_activation : 'softplus'
n_classes : 1
continue_training : False

dir_out : 'data_overhaul_test'
optimizer : 'adam'
batch_size : 100
max_epochs : 20
n_noimprovement_repeats : 10
output_directory : None
validation_fold : 0
loss_metric : 'mae'
