raw_files:
  feature_files: null
  response_files: null
  boundary_files: null
  feature_data_type: null
  response_data_type: null
  feature_nodata_value: -9999
  response_nodata_value: -9999
  boundary_bad_value: null
  ignore_projections: false
data_build:
  dir_out: .
  filename_prefix_out: ''
  response_data_format: FCN
  random_seed: 1
  max_samples: null
  number_folds: 10
  validation_fold: 0
  test_fold: null
  window_radius: null
  loss_window_radius: null
  feature_mean_centering: false
  feature_nodata_maximum_fraction: 0.0
  response_min_value: null
  response_max_value: null
  response_background_value: null
data_samples:
  apply_random_transformations: false
  batch_size: 100
  feature_scaler_names: null
  response_scaler_names: null
  feature_nodata_encoding: -10.0
model_training:
  dir_out: .
  verbosity: 1
  assert_gpu: false
  architecture_name: flat_net
  loss_metric: null
  max_epochs: 100
  optimizer: adam
  weighted: false
callback_general:
  checkpoint_periods: 5
  use_terminate_on_nan: true
callback_tensorboard:
  use_callback: true
  update_freq: epoch
  histogram_freq: 0
  write_graph: true
  write_grads: false
  write_images: true
callback_early_stopping:
  use_callback: true
  min_delta: 0.0001
  patience: 50
callback_reduced_learning_rate:
  use_callback: true
  factor: 0.5
  min_delta: 0.0001
  patience: 10
