raw_files:
  ignore_projections:
  features:
    featurename1:
      files:
      data_type:
      nodata_value:
      min_value: REQUIRED
      max_value: REQUIRED
      scaler_name:
    featurename2:
      files:
      data_type:
      nodata_value:
      min_value: REQUIRED
      max_value: REQUIRED
      scaler_name:
  responses:
    responsename1:
      files:
      data_type:
      nodata_value:
      min_value: REQUIRED
      max_value: REQUIRED
      scaler_name:
  boundaries:
    files:
    bad_value
data_build:
  random_seed: REQUIRED
  dir_out: REQUIRED
  filename_prefix_out: REQUIRED
  network_category: FCN
  data_build_category: or
  max_samples: REQUIRED
  max_memmap_size_gb: 10
  window_radius: REQUIRED
  loss_window_radius: REQUIRED
  number_folds: 10
  validation_fold: 0
  test_fold: 1
  feature_mean_centering: false
  feature_nodata_maximum_fraction: 0.0
  response_background_value: REQUIRED
data_samples:
  apply_random_transformations: false
  batch_size: 100
  feature_nodata_encoding: -10.0
model_training:
  dir_out: REQUIRED
  verbosity: 1
  assert_gpu: false
  architecture_name: dilation_net
  loss_metric: REQUIRED
  max_epochs: 100
  optimizer: adam
  weighted: false
architecture_options:
  block_structure: [1, 1, 1, 1]
  dilation_rate: 2
  filters: 64
  kernel_size: [3, 3]
  min_conv_width: 8
  n_classes: REQUIRED
  num_layers: 8
  optimizer: adam
  output_activation: REQUIRED
  padding: same
  pool_size: [2, 2]
  use_batch_norm: true
  use_growth: false
  use_initial_colorspaced_transformation_layer: false
callback_general:
  checkpoint_periods: 5
  use_terminate_on_nan: true
callback_tensorboard:
  use_callback: true
  update_freq: epoch
  histogram_freq: 0
  write_graph: true
  write_grads: false
  write_images: true
callback_early_stopping:
  use_callback: true
  min_delta: 0.0001
  patience: 50
callback_reduced_learning_rate:
  use_callback: true
  factor: 0.5
  min_delta: 0.0001
  patience: 10
