raw_files:
  raw_feature_file_list: REQUIRED
  raw_response_file_list: REQUIRED
  boundary_file_list: REQUIRED
  feature_raw_band_type_input: REQUIRED
  response_raw_band_type_input: REQUIRED
  feature_nodata_value: -9999
  response_nodata_value: -9999
  boundary_bad_value: REQUIRED
  ignore_projections: false
data_build:
  dir_data_out: REQUIRED
  response_data_format: FCN
  data_build_category: or
  data_save_name: REQUIRED
  random_seed: REQUIRED
  max_samples: REQUIRED
  n_folds: 10
  validation_fold: REQUIRED
  test_fold: REQUIRED
  window_radius: REQUIRED
  internal_window_radius: REQUIRED
  feature_mean_centering: false
  feature_nodata_maximum_fraction: 0.0
  response_min_value: REQUIRED
  response_max_value: REQUIRED
  response_background_value: REQUIRED
data_samples:
  apply_random_transformations: false
  batch_size: 100
  feature_scaler_names_list: REQUIRED
  response_scaler_names_list: REQUIRED
  feature_training_nodata_value: -10.0
model_training:
  dir_model_out: REQUIRED
  verbosity: 1
  assert_gpu: false
  architecture_name: residual_dilation_net
  loss_metric: REQUIRED
  max_epochs: 100
  n_classes: REQUIRED
  optimizer: adam
  output_activation: REQUIRED
  weighted: false
callback_general:
  checkpoint_periods: 5
  use_terminate_on_nan: true
callback_tensorboard:
  use_tensorboard: true
  dirname_prefix_tensorboard: tensorboard
  update_freq: epoch
  histogram_freq: 0
  write_graph: true
  write_grads: false
  write_images: true
callback_early_stopping:
  use_early_stopping: true
  min_delta: 0.0001
  patience: 50
callback_reduced_learning_rate:
  use_reduced_learning_rate: true
  factor: 0.5
  min_delta: 0.0001
  patience: 10
architecture_options:
  filters: 64
  inshape: REQUIRED
  kernel_size: [3, 3]
  n_classes: REQUIRED
  optimizer: adam
  output_activation: REQUIRED
  padding: same
  use_batch_norm: true
  use_initial_colorspaced_transformation_layer: false
  block_structure: [2, 2, 2, 2]
  min_conv_width: 8
  pool_size: [2, 2]
  use_growth: false
  dilation_rate: 2
  num_layers: 8
